include(
    ":android-integration-tests",
    ":comparison",
    ":injekt-android",
    ":injekt-android-work",
    ":injekt-compiler-plugin",
    ":injekt-core",
    ":injekt-gradle-plugin",
    ":integration-tests",
    ":sample",
    ":test-util"
)