include(
    ":injekt-android",
    ":injekt-android-work",
    ":injekt-common",
    ":injekt-compiler-plugin",
    ":injekt-core",
    ":injekt-coroutines",
    ":injekt-gradle-plugin",
    ":injekt-ide-plugin",
    ":injekt-scope",
    ":injekt-symbol-processor",
    ":integration-tests",
    ":test-util",
    "samples:android-app",
    "samples:coffee-maker",
    ":samples:type-classes"
)
