include(
    ":comparison",
    ":injekt-android",
    ":injekt-android-compose",
    ":injekt-android-work",
    ":injekt-common",
    ":injekt-compiler-plugin",
    ":injekt-composition",
    ":injekt-core",
    ":injekt-gradle-plugin",
    ":integration-tests",
    ":sample",
    ":test-util"
)