/*
 * Copyright 2021 Manuel Wrage
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.ivianuu.injekt.internal

internal annotation class CallableInfo(
  val value0: String = "",
  val value1: String = "",
  val value2: String = "",
  val value3: String = "",
  val value4: String = "",
  val value5: String = "",
  val value6: String = "",
  val value7: String = "",
  val value8: String = "",
  val value9: String = "",
  val value10: String = "",
  val value11: String = "",
  val value12: String = "",
  val value13: String = "",
  val value14: String = "",
  val value15: String = "",
  val value16: String = "",
  val value17: String = "",
  val value18: String = "",
  val value19: String = "",
  val value20: String = "",
  val value21: String = "",
  val value22: String = "",
  val value23: String = "",
  val value24: String = "",
  val value25: String = "",
  val value26: String = "",
  val value27: String = "",
  val value28: String = "",
  val value29: String = "",
  val value30: String = "",
  val value31: String = "",
  val value32: String = "",
  val value33: String = "",
  val value34: String = "",
  val value35: String = "",
  val value36: String = "",
  val value37: String = "",
  val value38: String = "",
  val value39: String = "",
  val value40: String = "",
  val value41: String = "",
  val value42: String = "",
  val value43: String = "",
  val value44: String = "",
  val value45: String = "",
  val value46: String = "",
  val value47: String = "",
  val value48: String = "",
  val value49: String = ""
)

internal annotation class ClassifierInfo(
  val value0: String = "",
  val value1: String = "",
  val value2: String = "",
  val value3: String = "",
  val value4: String = "",
  val value5: String = "",
  val value6: String = "",
  val value7: String = "",
  val value8: String = "",
  val value9: String = "",
  val value10: String = "",
  val value11: String = "",
  val value12: String = "",
  val value13: String = "",
  val value14: String = "",
  val value15: String = "",
  val value16: String = "",
  val value17: String = "",
  val value18: String = "",
  val value19: String = "",
  val value20: String = "",
  val value21: String = "",
  val value22: String = "",
  val value23: String = "",
  val value24: String = "",
  val value25: String = "",
  val value26: String = "",
  val value27: String = "",
  val value28: String = "",
  val value29: String = "",
  val value30: String = "",
  val value31: String = "",
  val value32: String = "",
  val value33: String = "",
  val value34: String = "",
  val value35: String = "",
  val value36: String = "",
  val value37: String = "",
  val value38: String = "",
  val value39: String = "",
  val value40: String = "",
  val value41: String = "",
  val value42: String = "",
  val value43: String = "",
  val value44: String = "",
  val value45: String = "",
  val value46: String = "",
  val value47: String = "",
  val value48: String = "",
  val value49: String = ""
)

internal annotation class TypeParameterInfos(
  val value0: String = "",
  val value1: String = "",
  val value2: String = "",
  val value3: String = "",
  val value4: String = "",
  val value5: String = "",
  val value6: String = "",
  val value7: String = "",
  val value8: String = "",
  val value9: String = "",
  val value10: String = "",
  val value11: String = "",
  val value12: String = "",
  val value13: String = "",
  val value14: String = "",
  val value15: String = "",
  val value16: String = "",
  val value17: String = "",
  val value18: String = "",
  val value19: String = "",
  val value20: String = "",
  val value21: String = "",
  val value22: String = "",
  val value23: String = "",
  val value24: String = "",
  val value25: String = "",
  val value26: String = "",
  val value27: String = "",
  val value28: String = "",
  val value29: String = "",
  val value30: String = "",
  val value31: String = "",
  val value32: String = "",
  val value33: String = "",
  val value34: String = "",
  val value35: String = "",
  val value36: String = "",
  val value37: String = "",
  val value38: String = "",
  val value39: String = "",
  val value40: String = "",
  val value41: String = "",
  val value42: String = "",
  val value43: String = "",
  val value44: String = "",
  val value45: String = "",
  val value46: String = "",
  val value47: String = "",
  val value48: String = "",
  val value49: String = ""
)
