/*
 * Copyright 2018 Manuel Wrage
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.ivianuu.injekt.comparison

import com.ivianuu.injekt.Bind
import com.ivianuu.injekt.Factory
import javax.inject.Inject

@Bind @Factory class Fib1 @Inject constructor()
@Bind @Factory class Fib2 @Inject constructor()
@Bind @Factory class Fib3 @Inject constructor(val fibM1: Fib2, val fibM2: Fib1)
@Bind @Factory class Fib4 @Inject constructor(val fibM1: Fib3, val fibM2: Fib2)
@Bind @Factory class Fib5 @Inject constructor(val fibM1: Fib4, val fibM2: Fib3)
@Bind @Factory class Fib6 @Inject constructor(val fibM1: Fib5, val fibM2: Fib4)
@Bind @Factory class Fib7 @Inject constructor(val fibM1: Fib6, val fibM2: Fib5)
@Bind @Factory class Fib8 @Inject constructor(val fibM1: Fib7, val fibM2: Fib6)
@Bind @Factory class Fib9 @Inject constructor(val fibM1: Fib8, val fibM2: Fib7)
@Bind @Factory class Fib10 @Inject constructor(val fibM1: Fib9, val fibM2: Fib8)
@Bind @Factory class Fib11 @Inject constructor(val fibM1: Fib10, val fibM2: Fib9)
@Bind @Factory class Fib12 @Inject constructor(val fibM1: Fib11, val fibM2: Fib10)
@Bind @Factory class Fib13 @Inject constructor(val fibM1: Fib12, val fibM2: Fib11)
@Bind @Factory class Fib14 @Inject constructor(val fibM1: Fib13, val fibM2: Fib12)
@Bind @Factory class Fib15 @Inject constructor(val fibM1: Fib14, val fibM2: Fib13)
@Bind @Factory class Fib16 @Inject constructor(val fibM1: Fib15, val fibM2: Fib14)
@Bind @Factory class Fib17 @Inject constructor(val fibM1: Fib16, val fibM2: Fib15)
@Bind @Factory class Fib18 @Inject constructor(val fibM1: Fib17, val fibM2: Fib16)
@Bind @Factory class Fib19 @Inject constructor(val fibM1: Fib18, val fibM2: Fib17)
@Bind @Factory class Fib20 @Inject constructor(val fibM1: Fib19, val fibM2: Fib18)
@Bind @Factory class Fib21 @Inject constructor(val fibM1: Fib20, val fibM2: Fib19)
@Bind @Factory class Fib22 @Inject constructor(val fibM1: Fib21, val fibM2: Fib20)
@Bind @Factory class Fib23 @Inject constructor(val fibM1: Fib22, val fibM2: Fib21)
@Bind @Factory class Fib24 @Inject constructor(val fibM1: Fib23, val fibM2: Fib22)
@Bind @Factory class Fib25 @Inject constructor(val fibM1: Fib24, val fibM2: Fib23)
@Bind @Factory class Fib26 @Inject constructor(val fibM1: Fib25, val fibM2: Fib24)
@Bind @Factory class Fib27 @Inject constructor(val fibM1: Fib26, val fibM2: Fib25)
@Bind @Factory class Fib28 @Inject constructor(val fibM1: Fib27, val fibM2: Fib26)
@Bind @Factory class Fib29 @Inject constructor(val fibM1: Fib28, val fibM2: Fib27)
@Bind @Factory class Fib30 @Inject constructor(val fibM1: Fib29, val fibM2: Fib28)
@Bind @Factory class Fib31 @Inject constructor(val fibM1: Fib30, val fibM2: Fib29)
@Bind @Factory class Fib32 @Inject constructor(val fibM1: Fib31, val fibM2: Fib30)
@Bind @Factory class Fib33 @Inject constructor(val fibM1: Fib32, val fibM2: Fib31)
@Bind @Factory class Fib34 @Inject constructor(val fibM1: Fib33, val fibM2: Fib32)
@Bind @Factory class Fib35 @Inject constructor(val fibM1: Fib34, val fibM2: Fib33)
@Bind @Factory class Fib36 @Inject constructor(val fibM1: Fib35, val fibM2: Fib34)
@Bind @Factory class Fib37 @Inject constructor(val fibM1: Fib36, val fibM2: Fib35)
@Bind @Factory class Fib38 @Inject constructor(val fibM1: Fib37, val fibM2: Fib36)
@Bind @Factory class Fib39 @Inject constructor(val fibM1: Fib38, val fibM2: Fib37)
@Bind @Factory class Fib40 @Inject constructor(val fibM1: Fib39, val fibM2: Fib38)
@Bind @Factory class Fib41 @Inject constructor(val fibM1: Fib40, val fibM2: Fib39)
@Bind @Factory class Fib42 @Inject constructor(val fibM1: Fib41, val fibM2: Fib40)
@Bind @Factory class Fib43 @Inject constructor(val fibM1: Fib42, val fibM2: Fib41)
@Bind @Factory class Fib44 @Inject constructor(val fibM1: Fib43, val fibM2: Fib42)
@Bind @Factory class Fib45 @Inject constructor(val fibM1: Fib44, val fibM2: Fib43)
@Bind @Factory class Fib46 @Inject constructor(val fibM1: Fib45, val fibM2: Fib44)
@Bind @Factory class Fib47 @Inject constructor(val fibM1: Fib46, val fibM2: Fib45)
@Bind @Factory class Fib48 @Inject constructor(val fibM1: Fib47, val fibM2: Fib46)
@Bind @Factory class Fib49 @Inject constructor(val fibM1: Fib48, val fibM2: Fib47)
@Bind @Factory class Fib50 @Inject constructor(val fibM1: Fib49, val fibM2: Fib48)
@Bind @Factory class Fib51 @Inject constructor(val fibM1: Fib50, val fibM2: Fib49)
@Bind @Factory class Fib52 @Inject constructor(val fibM1: Fib51, val fibM2: Fib50)
@Bind @Factory class Fib53 @Inject constructor(val fibM1: Fib52, val fibM2: Fib51)
@Bind @Factory class Fib54 @Inject constructor(val fibM1: Fib53, val fibM2: Fib52)
@Bind @Factory class Fib55 @Inject constructor(val fibM1: Fib54, val fibM2: Fib53)
@Bind @Factory class Fib56 @Inject constructor(val fibM1: Fib55, val fibM2: Fib54)
@Bind @Factory class Fib57 @Inject constructor(val fibM1: Fib56, val fibM2: Fib55)
@Bind @Factory class Fib58 @Inject constructor(val fibM1: Fib57, val fibM2: Fib56)
@Bind @Factory class Fib59 @Inject constructor(val fibM1: Fib58, val fibM2: Fib57)
@Bind @Factory class Fib60 @Inject constructor(val fibM1: Fib59, val fibM2: Fib58)
@Bind @Factory class Fib61 @Inject constructor(val fibM1: Fib60, val fibM2: Fib59)
@Bind @Factory class Fib62 @Inject constructor(val fibM1: Fib61, val fibM2: Fib60)
@Bind @Factory class Fib63 @Inject constructor(val fibM1: Fib62, val fibM2: Fib61)
@Bind @Factory class Fib64 @Inject constructor(val fibM1: Fib63, val fibM2: Fib62)
@Bind @Factory class Fib65 @Inject constructor(val fibM1: Fib64, val fibM2: Fib63)
@Bind @Factory class Fib66 @Inject constructor(val fibM1: Fib65, val fibM2: Fib64)
@Bind @Factory class Fib67 @Inject constructor(val fibM1: Fib66, val fibM2: Fib65)
@Bind @Factory class Fib68 @Inject constructor(val fibM1: Fib67, val fibM2: Fib66)
@Bind @Factory class Fib69 @Inject constructor(val fibM1: Fib68, val fibM2: Fib67)
@Bind @Factory class Fib70 @Inject constructor(val fibM1: Fib69, val fibM2: Fib68)
@Bind @Factory class Fib71 @Inject constructor(val fibM1: Fib70, val fibM2: Fib69)
@Bind @Factory class Fib72 @Inject constructor(val fibM1: Fib71, val fibM2: Fib70)
@Bind @Factory class Fib73 @Inject constructor(val fibM1: Fib72, val fibM2: Fib71)
@Bind @Factory class Fib74 @Inject constructor(val fibM1: Fib73, val fibM2: Fib72)
@Bind @Factory class Fib75 @Inject constructor(val fibM1: Fib74, val fibM2: Fib73)
@Bind @Factory class Fib76 @Inject constructor(val fibM1: Fib75, val fibM2: Fib74)
@Bind @Factory class Fib77 @Inject constructor(val fibM1: Fib76, val fibM2: Fib75)
@Bind @Factory class Fib78 @Inject constructor(val fibM1: Fib77, val fibM2: Fib76)
@Bind @Factory class Fib79 @Inject constructor(val fibM1: Fib78, val fibM2: Fib77)
@Bind @Factory class Fib80 @Inject constructor(val fibM1: Fib79, val fibM2: Fib78)
@Bind @Factory class Fib81 @Inject constructor(val fibM1: Fib80, val fibM2: Fib79)
@Bind @Factory class Fib82 @Inject constructor(val fibM1: Fib81, val fibM2: Fib80)
@Bind @Factory class Fib83 @Inject constructor(val fibM1: Fib82, val fibM2: Fib81)
@Bind @Factory class Fib84 @Inject constructor(val fibM1: Fib83, val fibM2: Fib82)
@Bind @Factory class Fib85 @Inject constructor(val fibM1: Fib84, val fibM2: Fib83)
@Bind @Factory class Fib86 @Inject constructor(val fibM1: Fib85, val fibM2: Fib84)
@Bind @Factory class Fib87 @Inject constructor(val fibM1: Fib86, val fibM2: Fib85)
@Bind @Factory class Fib88 @Inject constructor(val fibM1: Fib87, val fibM2: Fib86)
@Bind @Factory class Fib89 @Inject constructor(val fibM1: Fib88, val fibM2: Fib87)
@Bind @Factory class Fib90 @Inject constructor(val fibM1: Fib89, val fibM2: Fib88)
@Bind @Factory class Fib91 @Inject constructor(val fibM1: Fib90, val fibM2: Fib89)
@Bind @Factory class Fib92 @Inject constructor(val fibM1: Fib91, val fibM2: Fib90)
@Bind @Factory class Fib93 @Inject constructor(val fibM1: Fib92, val fibM2: Fib91)
@Bind @Factory class Fib94 @Inject constructor(val fibM1: Fib93, val fibM2: Fib92)
@Bind @Factory class Fib95 @Inject constructor(val fibM1: Fib94, val fibM2: Fib93)
@Bind @Factory class Fib96 @Inject constructor(val fibM1: Fib95, val fibM2: Fib94)
@Bind @Factory class Fib97 @Inject constructor(val fibM1: Fib96, val fibM2: Fib95)
@Bind @Factory class Fib98 @Inject constructor(val fibM1: Fib97, val fibM2: Fib96)
@Bind @Factory class Fib99 @Inject constructor(val fibM1: Fib98, val fibM2: Fib97)
@Bind @Factory class Fib100 @Inject constructor(val fibM1: Fib99, val fibM2: Fib98)