/*
 * Copyright 2018 Manuel Wrage
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.ivianuu.injekt.comparison.injektoptimized

import com.ivianuu.injekt.bind
import com.ivianuu.injekt.module

val injektOptimizedModule = createModule()

fun createModule() = module {
   bind(Fib1Binding())
   bind(Fib2Binding())
   bind(UnlinkedFib3Binding())
   bind(UnlinkedFib4Binding())
   bind(UnlinkedFib5Binding())
   bind(UnlinkedFib6Binding())
   bind(UnlinkedFib7Binding())
   bind(UnlinkedFib8Binding())
   bind(UnlinkedFib9Binding())
   bind(UnlinkedFib10Binding())
   bind(UnlinkedFib11Binding())
   bind(UnlinkedFib12Binding())
   bind(UnlinkedFib13Binding())
   bind(UnlinkedFib14Binding())
   bind(UnlinkedFib15Binding())
   bind(UnlinkedFib16Binding())
   bind(UnlinkedFib17Binding())
   bind(UnlinkedFib18Binding())
   bind(UnlinkedFib19Binding())
   bind(UnlinkedFib20Binding())
   bind(UnlinkedFib21Binding())
   bind(UnlinkedFib22Binding())
   bind(UnlinkedFib23Binding())
   bind(UnlinkedFib24Binding())
   bind(UnlinkedFib25Binding())
   bind(UnlinkedFib26Binding())
   bind(UnlinkedFib27Binding())
   bind(UnlinkedFib28Binding())
   bind(UnlinkedFib29Binding())
   bind(UnlinkedFib30Binding())
   bind(UnlinkedFib31Binding())
   bind(UnlinkedFib32Binding())
   bind(UnlinkedFib33Binding())
   bind(UnlinkedFib34Binding())
   bind(UnlinkedFib35Binding())
   bind(UnlinkedFib36Binding())
   bind(UnlinkedFib37Binding())
   bind(UnlinkedFib38Binding())
   bind(UnlinkedFib39Binding())
   bind(UnlinkedFib40Binding())
   bind(UnlinkedFib41Binding())
   bind(UnlinkedFib42Binding())
   bind(UnlinkedFib43Binding())
   bind(UnlinkedFib44Binding())
   bind(UnlinkedFib45Binding())
   bind(UnlinkedFib46Binding())
   bind(UnlinkedFib47Binding())
   bind(UnlinkedFib48Binding())
   bind(UnlinkedFib49Binding())
   bind(UnlinkedFib50Binding())
   bind(UnlinkedFib51Binding())
   bind(UnlinkedFib52Binding())
   bind(UnlinkedFib53Binding())
   bind(UnlinkedFib54Binding())
   bind(UnlinkedFib55Binding())
   bind(UnlinkedFib56Binding())
   bind(UnlinkedFib57Binding())
   bind(UnlinkedFib58Binding())
   bind(UnlinkedFib59Binding())
   bind(UnlinkedFib60Binding())
   bind(UnlinkedFib61Binding())
   bind(UnlinkedFib62Binding())
   bind(UnlinkedFib63Binding())
   bind(UnlinkedFib64Binding())
   bind(UnlinkedFib65Binding())
   bind(UnlinkedFib66Binding())
   bind(UnlinkedFib67Binding())
   bind(UnlinkedFib68Binding())
   bind(UnlinkedFib69Binding())
   bind(UnlinkedFib70Binding())
   bind(UnlinkedFib71Binding())
   bind(UnlinkedFib72Binding())
   bind(UnlinkedFib73Binding())
   bind(UnlinkedFib74Binding())
   bind(UnlinkedFib75Binding())
   bind(UnlinkedFib76Binding())
   bind(UnlinkedFib77Binding())
   bind(UnlinkedFib78Binding())
   bind(UnlinkedFib79Binding())
   bind(UnlinkedFib80Binding())
   bind(UnlinkedFib81Binding())
   bind(UnlinkedFib82Binding())
   bind(UnlinkedFib83Binding())
   bind(UnlinkedFib84Binding())
   bind(UnlinkedFib85Binding())
   bind(UnlinkedFib86Binding())
   bind(UnlinkedFib87Binding())
   bind(UnlinkedFib88Binding())
   bind(UnlinkedFib89Binding())
   bind(UnlinkedFib90Binding())
   bind(UnlinkedFib91Binding())
   bind(UnlinkedFib92Binding())
   bind(UnlinkedFib93Binding())
   bind(UnlinkedFib94Binding())
   bind(UnlinkedFib95Binding())
   bind(UnlinkedFib96Binding())
   bind(UnlinkedFib97Binding())
   bind(UnlinkedFib98Binding())
   bind(UnlinkedFib99Binding())
   bind(UnlinkedFib100Binding())
}